module.exports = {
  mainSidebar: [
    "home",
    {
      type: "category",
      label: "Info",
      collapsed: true,
      items: ["laws", "privacy", "security", "ad-blocking"],
    },
    {
      type: "category",
      label: "Content Type",
      collapsed: true,
      items: [
        "cartoons-and-anime",
        "comics-and-manga",
        "books-and-magazines",
        "academics",
        "courses",
        "documentaries",
        "audiobooks",
        "music-and-podcasts",
        "movies-and-tv-shows",
        "sports",
        "games",
        "software",
        "creative-assets",
      ],
    },
    {
      type: "category",
      label: "Sources",
      collapsed: true,
      items: [
        "torrents",
        "usenet",
        "direct-downloads",
        "discord",
        "irc",
        "telegram",
        "dc-plus-plus",
        "iptv",
      ],
    },
    {
      type: "category",
      label: "Miscellaneous",
      collapsed: true,
      items: [
        "browser-extensions",
        "userscripts",
        "paywalls",
        "file-sharing",
        "cloud-storage",
        "media-centre-applications",
        "alt-google",
        "tools",
        "misc",
        "dead",
      ],
    },
  ],
};
